version: "3.9"

services:
  backend:
    build: .
    container_name: fisioclininc_backend
    restart: always
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - .env
    ports:
      - "8000:8000"     # ‚Üê Agregar esto
